// Generated by ffigen. Do not edit manually.
// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for Verovio FFI wrapper
class VerovioNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VerovioNativeBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VerovioNativeBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  VrvToolkitHandle vrv_ffi_create(
    ffi.Pointer<ffi.Char> resource_path,
  ) {
    return _vrv_ffi_create(
      resource_path,
    );
  }

  late final _vrv_ffi_createPtr = _lookup<
          ffi.NativeFunction<VrvToolkitHandle Function(ffi.Pointer<ffi.Char>)>>(
      'vrv_ffi_create');
  late final _vrv_ffi_create = _vrv_ffi_createPtr
      .asFunction<VrvToolkitHandle Function(ffi.Pointer<ffi.Char>)>();

  void vrv_ffi_destroy(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_destroy(
      handle,
    );
  }

  late final _vrv_ffi_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VrvToolkitHandle)>>(
          'vrv_ffi_destroy');
  late final _vrv_ffi_destroy =
      _vrv_ffi_destroyPtr.asFunction<void Function(VrvToolkitHandle)>();

  bool vrv_ffi_set_resource_path(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> resource_path,
  ) {
    return _vrv_ffi_set_resource_path(
      handle,
      resource_path,
    );
  }

  late final _vrv_ffi_set_resource_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_set_resource_path');
  late final _vrv_ffi_set_resource_path = _vrv_ffi_set_resource_pathPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_set_options_json(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> options_json,
  ) {
    return _vrv_ffi_set_options_json(
      handle,
      options_json,
    );
  }

  late final _vrv_ffi_set_options_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_set_options_json');
  late final _vrv_ffi_set_options_json = _vrv_ffi_set_options_jsonPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_load_data(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> utf8_data,
  ) {
    return _vrv_ffi_load_data(
      handle,
      utf8_data,
    );
  }

  late final _vrv_ffi_load_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>>('vrv_ffi_load_data');
  late final _vrv_ffi_load_data = _vrv_ffi_load_dataPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_load_zip_data_base64(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> base64_data,
  ) {
    return _vrv_ffi_load_zip_data_base64(
      handle,
      base64_data,
    );
  }

  late final _vrv_ffi_load_zip_data_base64Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_load_zip_data_base64');
  late final _vrv_ffi_load_zip_data_base64 = _vrv_ffi_load_zip_data_base64Ptr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  int vrv_ffi_get_page_count(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_page_count(
      handle,
    );
  }

  late final _vrv_ffi_get_page_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(VrvToolkitHandle)>>(
          'vrv_ffi_get_page_count');
  late final _vrv_ffi_get_page_count =
      _vrv_ffi_get_page_countPtr.asFunction<int Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_to_svg(
    VrvToolkitHandle handle,
    int page_no,
    bool xml_declaration,
  ) {
    return _vrv_ffi_render_to_svg(
      handle,
      page_no,
      xml_declaration,
    );
  }

  late final _vrv_ffi_render_to_svgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Int32, ffi.Bool)>>('vrv_ffi_render_to_svg');
  late final _vrv_ffi_render_to_svg = _vrv_ffi_render_to_svgPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(VrvToolkitHandle, int, bool)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_log(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_log(
      handle,
    );
  }

  late final _vrv_ffi_get_logPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_log');
  late final _vrv_ffi_get_log = _vrv_ffi_get_logPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_version(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_version(
      handle,
    );
  }

  late final _vrv_ffi_get_versionPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_version');
  late final _vrv_ffi_get_version = _vrv_ffi_get_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_to_midi(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_render_to_midi(
      handle,
    );
  }

  late final _vrv_ffi_render_to_midiPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_render_to_midi');
  late final _vrv_ffi_render_to_midi = _vrv_ffi_render_to_midiPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_to_pae(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_render_to_pae(
      handle,
    );
  }

  late final _vrv_ffi_render_to_paePtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_render_to_pae');
  late final _vrv_ffi_render_to_pae = _vrv_ffi_render_to_paePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_to_timemap(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> json_options,
  ) {
    return _vrv_ffi_render_to_timemap(
      handle,
      json_options,
    );
  }

  late final _vrv_ffi_render_to_timemapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_render_to_timemap');
  late final _vrv_ffi_render_to_timemap =
      _vrv_ffi_render_to_timemapPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_to_expansion_map(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_render_to_expansion_map(
      handle,
    );
  }

  late final _vrv_ffi_render_to_expansion_mapPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_render_to_expansion_map');
  late final _vrv_ffi_render_to_expansion_map =
      _vrv_ffi_render_to_expansion_mapPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  int vrv_ffi_get_scale(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_scale(
      handle,
    );
  }

  late final _vrv_ffi_get_scalePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(VrvToolkitHandle)>>(
          'vrv_ffi_get_scale');
  late final _vrv_ffi_get_scale =
      _vrv_ffi_get_scalePtr.asFunction<int Function(VrvToolkitHandle)>();

  bool vrv_ffi_set_scale(
    VrvToolkitHandle handle,
    int scale,
  ) {
    return _vrv_ffi_set_scale(
      handle,
      scale,
    );
  }

  late final _vrv_ffi_set_scalePtr = _lookup<
          ffi.NativeFunction<ffi.Bool Function(VrvToolkitHandle, ffi.Int32)>>(
      'vrv_ffi_set_scale');
  late final _vrv_ffi_set_scale =
      _vrv_ffi_set_scalePtr.asFunction<bool Function(VrvToolkitHandle, int)>();

  int vrv_ffi_get_page_with_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_page_with_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_page_with_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_page_with_element');
  late final _vrv_ffi_get_page_with_element = _vrv_ffi_get_page_with_elementPtr
      .asFunction<int Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  int vrv_ffi_get_time_for_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_time_for_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_time_for_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_time_for_element');
  late final _vrv_ffi_get_time_for_element = _vrv_ffi_get_time_for_elementPtr
      .asFunction<int Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_select(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> selection_json,
  ) {
    return _vrv_ffi_select(
      handle,
      selection_json,
    );
  }

  late final _vrv_ffi_selectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>>('vrv_ffi_select');
  late final _vrv_ffi_select = _vrv_ffi_selectPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_set_input_from(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> input_from,
  ) {
    return _vrv_ffi_set_input_from(
      handle,
      input_from,
    );
  }

  late final _vrv_ffi_set_input_fromPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_set_input_from');
  late final _vrv_ffi_set_input_from = _vrv_ffi_set_input_fromPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_set_output_to(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> output_to,
  ) {
    return _vrv_ffi_set_output_to(
      handle,
      output_to,
    );
  }

  late final _vrv_ffi_set_output_toPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_set_output_to');
  late final _vrv_ffi_set_output_to = _vrv_ffi_set_output_toPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  bool vrv_ffi_edit(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> editor_action,
  ) {
    return _vrv_ffi_edit(
      handle,
      editor_action,
    );
  }

  late final _vrv_ffi_editPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>>('vrv_ffi_edit');
  late final _vrv_ffi_edit = _vrv_ffi_editPtr
      .asFunction<bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_available_options(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_available_options(
      handle,
    );
  }

  late final _vrv_ffi_get_available_optionsPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_available_options');
  late final _vrv_ffi_get_available_options = _vrv_ffi_get_available_optionsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_default_options(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_default_options(
      handle,
    );
  }

  late final _vrv_ffi_get_default_optionsPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_default_options');
  late final _vrv_ffi_get_default_options = _vrv_ffi_get_default_optionsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_options(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_options(
      handle,
    );
  }

  late final _vrv_ffi_get_optionsPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_options');
  late final _vrv_ffi_get_options = _vrv_ffi_get_optionsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_option_usage_string(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_option_usage_string(
      handle,
    );
  }

  late final _vrv_ffi_get_option_usage_stringPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_option_usage_string');
  late final _vrv_ffi_get_option_usage_string =
      _vrv_ffi_get_option_usage_stringPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_descriptive_features(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> json_options,
  ) {
    return _vrv_ffi_get_descriptive_features(
      handle,
      json_options,
    );
  }

  late final _vrv_ffi_get_descriptive_featuresPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_descriptive_features');
  late final _vrv_ffi_get_descriptive_features =
      _vrv_ffi_get_descriptive_featuresPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_element_attr(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_element_attr(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_element_attrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_element_attr');
  late final _vrv_ffi_get_element_attr =
      _vrv_ffi_get_element_attrPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_elements_at_time(
    VrvToolkitHandle handle,
    int millisec,
  ) {
    return _vrv_ffi_get_elements_at_time(
      handle,
      millisec,
    );
  }

  late final _vrv_ffi_get_elements_at_timePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Int32)>>('vrv_ffi_get_elements_at_time');
  late final _vrv_ffi_get_elements_at_time = _vrv_ffi_get_elements_at_timePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle, int)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_expansion_ids_for_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_expansion_ids_for_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_expansion_ids_for_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_expansion_ids_for_element');
  late final _vrv_ffi_get_expansion_ids_for_element =
      _vrv_ffi_get_expansion_ids_for_elementPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_midi_values_for_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_midi_values_for_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_midi_values_for_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_midi_values_for_element');
  late final _vrv_ffi_get_midi_values_for_element =
      _vrv_ffi_get_midi_values_for_elementPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_notated_id_for_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_notated_id_for_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_notated_id_for_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_notated_id_for_element');
  late final _vrv_ffi_get_notated_id_for_element =
      _vrv_ffi_get_notated_id_for_elementPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_times_for_element(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> xml_id,
  ) {
    return _vrv_ffi_get_times_for_element(
      handle,
      xml_id,
    );
  }

  late final _vrv_ffi_get_times_for_elementPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_times_for_element');
  late final _vrv_ffi_get_times_for_element =
      _vrv_ffi_get_times_for_elementPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_id(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_id(
      handle,
    );
  }

  late final _vrv_ffi_get_idPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_id');
  late final _vrv_ffi_get_id = _vrv_ffi_get_idPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_resource_path(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_resource_path(
      handle,
    );
  }

  late final _vrv_ffi_get_resource_pathPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_resource_path');
  late final _vrv_ffi_get_resource_path = _vrv_ffi_get_resource_pathPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_humdrum(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_get_humdrum(
      handle,
    );
  }

  late final _vrv_ffi_get_humdrumPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_get_humdrum');
  late final _vrv_ffi_get_humdrum = _vrv_ffi_get_humdrumPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_get_mei(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> json_options,
  ) {
    return _vrv_ffi_get_mei(
      handle,
      json_options,
    );
  }

  late final _vrv_ffi_get_meiPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>>('vrv_ffi_get_mei');
  late final _vrv_ffi_get_mei = _vrv_ffi_get_meiPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_convert_humdrum_to_humdrum(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> humdrum_data,
  ) {
    return _vrv_ffi_convert_humdrum_to_humdrum(
      handle,
      humdrum_data,
    );
  }

  late final _vrv_ffi_convert_humdrum_to_humdrumPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_convert_humdrum_to_humdrum');
  late final _vrv_ffi_convert_humdrum_to_humdrum =
      _vrv_ffi_convert_humdrum_to_humdrumPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_convert_humdrum_to_midi(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> humdrum_data,
  ) {
    return _vrv_ffi_convert_humdrum_to_midi(
      handle,
      humdrum_data,
    );
  }

  late final _vrv_ffi_convert_humdrum_to_midiPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_convert_humdrum_to_midi');
  late final _vrv_ffi_convert_humdrum_to_midi =
      _vrv_ffi_convert_humdrum_to_midiPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_convert_mei_to_humdrum(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> mei_data,
  ) {
    return _vrv_ffi_convert_mei_to_humdrum(
      handle,
      mei_data,
    );
  }

  late final _vrv_ffi_convert_mei_to_humdrumPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_convert_mei_to_humdrum');
  late final _vrv_ffi_convert_mei_to_humdrum =
      _vrv_ffi_convert_mei_to_humdrumPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_edit_info(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_edit_info(
      handle,
    );
  }

  late final _vrv_ffi_edit_infoPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>>(
      'vrv_ffi_edit_info');
  late final _vrv_ffi_edit_info = _vrv_ffi_edit_infoPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(VrvToolkitHandle)>();

  ffi.Pointer<ffi.Char> vrv_ffi_validate_pae(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> data,
  ) {
    return _vrv_ffi_validate_pae(
      handle,
      data,
    );
  }

  late final _vrv_ffi_validate_paePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(VrvToolkitHandle,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_validate_pae');
  late final _vrv_ffi_validate_pae = _vrv_ffi_validate_paePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> vrv_ffi_render_data(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> data,
    ffi.Pointer<ffi.Char> json_options,
  ) {
    return _vrv_ffi_render_data(
      handle,
      data,
      json_options,
    );
  }

  late final _vrv_ffi_render_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              VrvToolkitHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('vrv_ffi_render_data');
  late final _vrv_ffi_render_data = _vrv_ffi_render_dataPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          VrvToolkitHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  void vrv_ffi_redo_layout(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Char> json_options,
  ) {
    return _vrv_ffi_redo_layout(
      handle,
      json_options,
    );
  }

  late final _vrv_ffi_redo_layoutPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              VrvToolkitHandle, ffi.Pointer<ffi.Char>)>>('vrv_ffi_redo_layout');
  late final _vrv_ffi_redo_layout = _vrv_ffi_redo_layoutPtr
      .asFunction<void Function(VrvToolkitHandle, ffi.Pointer<ffi.Char>)>();

  void vrv_ffi_redo_page_pitch_pos_layout(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_redo_page_pitch_pos_layout(
      handle,
    );
  }

  late final _vrv_ffi_redo_page_pitch_pos_layoutPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VrvToolkitHandle)>>(
          'vrv_ffi_redo_page_pitch_pos_layout');
  late final _vrv_ffi_redo_page_pitch_pos_layout =
      _vrv_ffi_redo_page_pitch_pos_layoutPtr
          .asFunction<void Function(VrvToolkitHandle)>();

  void vrv_ffi_reset_options(
    VrvToolkitHandle handle,
  ) {
    return _vrv_ffi_reset_options(
      handle,
    );
  }

  late final _vrv_ffi_reset_optionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VrvToolkitHandle)>>(
          'vrv_ffi_reset_options');
  late final _vrv_ffi_reset_options =
      _vrv_ffi_reset_optionsPtr.asFunction<void Function(VrvToolkitHandle)>();

  void vrv_ffi_reset_xml_id_seed(
    VrvToolkitHandle handle,
    int seed,
  ) {
    return _vrv_ffi_reset_xml_id_seed(
      handle,
      seed,
    );
  }

  late final _vrv_ffi_reset_xml_id_seedPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(VrvToolkitHandle, ffi.Int32)>>(
      'vrv_ffi_reset_xml_id_seed');
  late final _vrv_ffi_reset_xml_id_seed = _vrv_ffi_reset_xml_id_seedPtr
      .asFunction<void Function(VrvToolkitHandle, int)>();

  bool vrv_ffi_load_zip_data_buffer(
    VrvToolkitHandle handle,
    ffi.Pointer<ffi.Uint8> data,
    int length,
  ) {
    return _vrv_ffi_load_zip_data_buffer(
      handle,
      data,
      length,
    );
  }

  late final _vrv_ffi_load_zip_data_bufferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Uint8>,
              ffi.Int32)>>('vrv_ffi_load_zip_data_buffer');
  late final _vrv_ffi_load_zip_data_buffer =
      _vrv_ffi_load_zip_data_bufferPtr.asFunction<
          bool Function(VrvToolkitHandle, ffi.Pointer<ffi.Uint8>, int)>();

  void vrv_ffi_string_free(
    ffi.Pointer<ffi.Char> s,
  ) {
    return _vrv_ffi_string_free(
      s,
    );
  }

  late final _vrv_ffi_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'vrv_ffi_string_free');
  late final _vrv_ffi_string_free = _vrv_ffi_string_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

final class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

typedef VrvToolkitHandle = ffi.Pointer<ffi.Void>;

const int __bool_true_false_are_defined = 1;

const int true1 = 1;

const int false1 = 0;

const int __WORDSIZE = 64;

const int __has_safe_buffers = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __has_bounds_safety_attributes = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;
