#ifndef all_h
#define all_h
#import <VerovioFFI/Binasc.h>
#import <VerovioFFI/MidiEvent.h>
#import <VerovioFFI/MidiEventList.h>
#import <VerovioFFI/MidiFile.h>
#import <VerovioFFI/MidiMessage.h>
#import <VerovioFFI/Tunings.h>
#import <VerovioFFI/TuningsConcepts.h>
#import <VerovioFFI/TuningsImpl.h>
#import <VerovioFFI/abbr.h>
#import <VerovioFFI/accid.h>
#import <VerovioFFI/add.h>
#import <VerovioFFI/adjustaccidxfunctor.h>
#import <VerovioFFI/adjustarpegfunctor.h>
#import <VerovioFFI/adjustarticfunctor.h>
#import <VerovioFFI/adjustbeamsfunctor.h>
#import <VerovioFFI/adjustclefchangesfunctor.h>
#import <VerovioFFI/adjustdotsfunctor.h>
#import <VerovioFFI/adjustfloatingpositionerfunctor.h>
#import <VerovioFFI/adjustgracexposfunctor.h>
#import <VerovioFFI/adjustharmgrpsspacingfunctor.h>
#import <VerovioFFI/adjustlayersfunctor.h>
#import <VerovioFFI/adjustneumexfunctor.h>
#import <VerovioFFI/adjustossiastaffdeffunctor.h>
#import <VerovioFFI/adjustslursfunctor.h>
#import <VerovioFFI/adjuststaffoverlapfunctor.h>
#import <VerovioFFI/adjustsylspacingfunctor.h>
#import <VerovioFFI/adjusttempofunctor.h>
#import <VerovioFFI/adjusttupletsxfunctor.h>
#import <VerovioFFI/adjusttupletsyfunctor.h>
#import <VerovioFFI/adjustxoverflowfunctor.h>
#import <VerovioFFI/adjustxposfunctor.h>
#import <VerovioFFI/adjustxrelfortranscriptionfunctor.h>
#import <VerovioFFI/adjustyposfunctor.h>
#import <VerovioFFI/adjustyrelfortranscriptionfunctor.h>
#import <VerovioFFI/alignfunctor.h>
#import <VerovioFFI/altsyminterface.h>
#import <VerovioFFI/anchoredtext.h>
#import <VerovioFFI/annot.h>
#import <VerovioFFI/annotscore.h>
#import <VerovioFFI/app.h>
#import <VerovioFFI/areaposinterface.h>
#import <VerovioFFI/arpeg.h>
#import <VerovioFFI/artic.h>
#import <VerovioFFI/barline.h>
#import <VerovioFFI/bboxdevicecontext.h>
#import <VerovioFFI/beam.h>
#import <VerovioFFI/beamspan.h>
#import <VerovioFFI/beatrpt.h>
#import <VerovioFFI/boundingbox.h>
#import <VerovioFFI/bracketspan.h>
#import <VerovioFFI/breath.h>
#import <VerovioFFI/btrem.h>
#import <VerovioFFI/cachehorizontallayoutfunctor.h>
#import <VerovioFFI/caesura.h>
#import <VerovioFFI/calcalignmentpitchposfunctor.h>
#import <VerovioFFI/calcalignmentxposfunctor.h>
#import <VerovioFFI/calcarticfunctor.h>
#import <VerovioFFI/calcbboxoverflowsfunctor.h>
#import <VerovioFFI/calcchordnoteheadsfunctor.h>
#import <VerovioFFI/calcdotsfunctor.h>
#import <VerovioFFI/calcledgerlinesfunctor.h>
#import <VerovioFFI/calcligatureorneumeposfunctor.h>
#import <VerovioFFI/calcslurdirectionfunctor.h>
#import <VerovioFFI/calcspanningbeamspansfunctor.h>
#import <VerovioFFI/calcstemfunctor.h>
#import <VerovioFFI/castofffunctor.h>
#import <VerovioFFI/choice.h>
#import <VerovioFFI/chord.h>
#import <VerovioFFI/clef.h>
#import <VerovioFFI/comparison.h>
#import <VerovioFFI/controlelement.h>
#import <VerovioFFI/convertfunctor.h>
#import <VerovioFFI/corr.h>
#import <VerovioFFI/course.h>
#import <VerovioFFI/cpmark.h>
#import <VerovioFFI/crc.h>
#import <VerovioFFI/customtuning.h>
#import <VerovioFFI/custos.h>
#import <VerovioFFI/damage.h>
#import <VerovioFFI/del.h>
#import <VerovioFFI/devicecontext.h>
#import <VerovioFFI/devicecontextbase.h>
#import <VerovioFFI/dir.h>
#import <VerovioFFI/div.h>
#import <VerovioFFI/divline.h>
#import <VerovioFFI/doc.h>
#import <VerovioFFI/docselection.h>
#import <VerovioFFI/dot.h>
#import <VerovioFFI/drawinginterface.h>
#import <VerovioFFI/durationinterface.h>
#import <VerovioFFI/dynam.h>
#import <VerovioFFI/editfunctor.h>
#import <VerovioFFI/editorial.h>
#import <VerovioFFI/editortoolkit.h>
#import <VerovioFFI/editortoolkit_cmn.h>
#import <VerovioFFI/editortoolkit_mensural.h>
#import <VerovioFFI/editortoolkit_neume.h>
#import <VerovioFFI/editortoolkit_shared.h>
#import <VerovioFFI/elementpart.h>
#import <VerovioFFI/ending.h>
#import <VerovioFFI/episema.h>
#import <VerovioFFI/expan.h>
#import <VerovioFFI/expansion.h>
#import <VerovioFFI/expansionmap.h>
#import <VerovioFFI/f.h>
#import <VerovioFFI/facsimile.h>
#import <VerovioFFI/facsimilefunctor.h>
#import <VerovioFFI/facsimileinterface.h>
#import <VerovioFFI/fb.h>
#import <VerovioFFI/featureextractor.h>
#import <VerovioFFI/fermata.h>
#import <VerovioFFI/fig.h>
#import <VerovioFFI/filereader.h>
#import <VerovioFFI/findfunctor.h>
#import <VerovioFFI/findlayerelementsfunctor.h>
#import <VerovioFFI/fing.h>
#import <VerovioFFI/floatingobject.h>
#import <VerovioFFI/fraction.h>
#import <VerovioFFI/ftrem.h>
#import <VerovioFFI/functor.h>
#import <VerovioFFI/functorinterface.h>
#import <VerovioFFI/genericlayerelement.h>
#import <VerovioFFI/git_commit.h>
#import <VerovioFFI/gliss.h>
#import <VerovioFFI/glyph.h>
#import <VerovioFFI/gracegrp.h>
#import <VerovioFFI/graphic.h>
#import <VerovioFFI/grpsym.h>
#import <VerovioFFI/hairpin.h>
#import <VerovioFFI/halfmrpt.h>
#import <VerovioFFI/harm.h>
#import <VerovioFFI/horizontalaligner.h>
#import <VerovioFFI/humlib.h>
#import <VerovioFFI/instrdef.h>
#import <VerovioFFI/interface.h>
#import <VerovioFFI/ioabc.h>
#import <VerovioFFI/iobase.h>
#import <VerovioFFI/iocmme.h>
#import <VerovioFFI/iodarms.h>
#import <VerovioFFI/iogabc.h>
#import <VerovioFFI/iohumdrum.h>
#import <VerovioFFI/iomei.h>
#import <VerovioFFI/iomusxml.h>
#import <VerovioFFI/iopae.h>
#import <VerovioFFI/iovolpiano.h>
#import <VerovioFFI/jsonxx.h>
#import <VerovioFFI/justifyfunctor.h>
#import <VerovioFFI/keyaccid.h>
#import <VerovioFFI/keysig.h>
#import <VerovioFFI/label.h>
#import <VerovioFFI/labelabbr.h>
#import <VerovioFFI/layer.h>
#import <VerovioFFI/layerdef.h>
#import <VerovioFFI/layerelement.h>
#import <VerovioFFI/lb.h>
#import <VerovioFFI/lem.h>
#import <VerovioFFI/libmei.h>
#import <VerovioFFI/ligature.h>
#import <VerovioFFI/linkinginterface.h>
#import <VerovioFFI/liquescent.h>
#import <VerovioFFI/lv.h>
#import <VerovioFFI/mdiv.h>
#import <VerovioFFI/measure.h>
#import <VerovioFFI/mensur.h>
#import <VerovioFFI/metersig.h>
#import <VerovioFFI/metersiggrp.h>
#import <VerovioFFI/midifunctor.h>
#import <VerovioFFI/miscfunctor.h>
#import <VerovioFFI/mnum.h>
#import <VerovioFFI/mordent.h>
#import <VerovioFFI/mrest.h>
#import <VerovioFFI/mrpt.h>
#import <VerovioFFI/mrpt2.h>
#import <VerovioFFI/mspace.h>
#import <VerovioFFI/multirest.h>
#import <VerovioFFI/multirpt.h>
#import <VerovioFFI/nc.h>
#import <VerovioFFI/neume.h>
#import <VerovioFFI/note.h>
#import <VerovioFFI/num.h>
#import <VerovioFFI/object.h>
#import <VerovioFFI/octave.h>
#import <VerovioFFI/offsetinterface.h>
#import <VerovioFFI/options.h>
#import <VerovioFFI/orig.h>
#import <VerovioFFI/oriscus.h>
#import <VerovioFFI/ornam.h>
#import <VerovioFFI/ossia.h>
#import <VerovioFFI/page.h>
#import <VerovioFFI/pageelement.h>
#import <VerovioFFI/pagemilestone.h>
#import <VerovioFFI/pages.h>
#import <VerovioFFI/pb.h>
#import <VerovioFFI/pedal.h>
#import <VerovioFFI/pgfoot.h>
#import <VerovioFFI/pghead.h>
#import <VerovioFFI/phrase.h>
#import <VerovioFFI/pitchinflection.h>
#import <VerovioFFI/pitchinterface.h>
#import <VerovioFFI/plica.h>
#import <VerovioFFI/plistinterface.h>
#import <VerovioFFI/positioninterface.h>
#import <VerovioFFI/preparedatafunctor.h>
#import <VerovioFFI/proport.h>
#import <VerovioFFI/quilisma.h>
#import <VerovioFFI/rdg.h>
#import <VerovioFFI/ref.h>
#import <VerovioFFI/reg.h>
#import <VerovioFFI/reh.h>
#import <VerovioFFI/rend.h>
#import <VerovioFFI/repeatmark.h>
#import <VerovioFFI/resetfunctor.h>
#import <VerovioFFI/resources.h>
#import <VerovioFFI/rest.h>
#import <VerovioFFI/restore.h>
#import <VerovioFFI/runningelement.h>
#import <VerovioFFI/runtimeclock.h>
#import <VerovioFFI/savefunctor.h>
#import <VerovioFFI/sb.h>
#import <VerovioFFI/score.h>
#import <VerovioFFI/scoredef.h>
#import <VerovioFFI/scoredefinterface.h>
#import <VerovioFFI/scoringupfunctor.h>
#import <VerovioFFI/section.h>
#import <VerovioFFI/setscoredeffunctor.h>
#import <VerovioFFI/sic.h>
#import <VerovioFFI/slur.h>
#import <VerovioFFI/smufl.h>
#import <VerovioFFI/space.h>
#import <VerovioFFI/staff.h>
#import <VerovioFFI/staffdef.h>
#import <VerovioFFI/staffgrp.h>
#import <VerovioFFI/stem.h>
#import <VerovioFFI/strophicus.h>
#import <VerovioFFI/subst.h>
#import <VerovioFFI/supplied.h>
#import <VerovioFFI/surface.h>
#import <VerovioFFI/svg.h>
#import <VerovioFFI/svgdevicecontext.h>
#import <VerovioFFI/syl.h>
#import <VerovioFFI/syllable.h>
#import <VerovioFFI/symbol.h>
#import <VerovioFFI/symboldef.h>
#import <VerovioFFI/symboltable.h>
#import <VerovioFFI/system.h>
#import <VerovioFFI/systemelement.h>
#import <VerovioFFI/systemmilestone.h>
#import <VerovioFFI/tabdursym.h>
#import <VerovioFFI/tabgrp.h>
#import <VerovioFFI/tempo.h>
#import <VerovioFFI/text.h>
#import <VerovioFFI/textdirinterface.h>
#import <VerovioFFI/textelement.h>
#import <VerovioFFI/textlayoutelement.h>
#import <VerovioFFI/tie.h>
#import <VerovioFFI/timeinterface.h>
#import <VerovioFFI/timemap.h>
#import <VerovioFFI/timestamp.h>
#import <VerovioFFI/toolkit.h>
#import <VerovioFFI/toolkitdef.h>
#import <VerovioFFI/transposefunctor.h>
#import <VerovioFFI/transposition.h>
#import <VerovioFFI/trill.h>
#import <VerovioFFI/tuning.h>
#import <VerovioFFI/tuplet.h>
#import <VerovioFFI/turn.h>
#import <VerovioFFI/unclear.h>
#import <VerovioFFI/verse.h>
#import <VerovioFFI/verticalaligner.h>
#import <VerovioFFI/view.h>
#import <VerovioFFI/vrv.h>
#import <VerovioFFI/vrvdef.h>
#import <VerovioFFI/zone.h>
#endif /* all_h */
